### PR TITLE
fix(): envoy icon

### PR DESCRIPTION
**Pull request by wilsonwu**
to correct size and view

### CODE REVIEW

**Comment by wilsonwu** [comment]
Icon here:
image

form 
image
change to
image

**Comment by wu-sheng** [comment]
Please compress the icon, `+19.6 KB (320%)`, this is too big.

**Comment by wilsonwu** [comment]
@wu-sheng done.

**Review by wu-sheng — APPROVED** [review]
If you want this be included in the release, please update the submodule of main repo.

**Pull request merged**
