### PR TITLE
Fix: fix date-components utc bug

### PR DESCRIPTION
**Pull request by TinyAllen**
Fix issue：https://github.com/apache/skywalking/issues/3791

image

### CODE REVIEW

**Comment by wu-sheng** [comment]
@JaredTan95 We should submit a JIRA ticket to make NODE CI as required jobs, and remove Travis CI.

**Comment by wu-sheng** [comment]
@JaredTan95 Could you help on sync master branch.

**Comment by JaredTan95** [comment]
> @JaredTan95 Could you help on sync master branch.

👌

**Comment by JaredTan95** [comment]
> @JaredTan95 We should submit a JIRA ticket to make NODE CI as required jobs, and remove Travis CI.

I wiil fowlling this.

**Pull request merged**
