### PR TITLE
Feat: Create a dashboard template using the default template

### PR DESCRIPTION
**Pull request by Fine0830**
Create a dashboard template using options of the default template. reference https://github.com/apache/skywalking/issues/4989

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why the APM configuration could be shown up in the NOC type? I think it is a standard template.

**Comment by Fine0830** [comment]
> Why the APM configuration could be shown up in the NOC type? I think it is a standard template.

Does NOC type need template configuration?

**Comment by wu-sheng** [comment]
> Does NOC type need template configuration?

That should base on the backend data, currently, it hasn't. I don't UI should assume maybe will have one.

**Comment by Fine0830** [comment]
It's done. Please recheck.

**Pull request merged**
