### PR TITLE
Feat: update topo chart

### PR DESCRIPTION
**Pull request by Fine0830**
The PR update charts style in topo page, charts are clearer.
屏幕快照 2019-11-27 上午9 56 36

### CODE REVIEW

**Comment by wu-sheng** [comment]
@Fine0830 Could you provide the preview when the metrics tab expands?

**Comment by Fine0830** [comment]
> @Fine0830 Could you provide the preview when the metrics tab expands?

Isn't it the picture above?

**Comment by wu-sheng** [comment]
Click this, the panel will expand.
image

**Comment by Fine0830** [comment]
> Click this, the panel will expand.
> image
Okay
屏幕快照 2019-11-27 上午10 48 11

**Comment by wu-sheng** [comment]
You could sync to main repo now.

**Comment by Fine0830** [comment]
> You could sync to main repo now.

Done!

**Pull request merged**
