### PR TITLE
Adjust the width of 'rk-sidebox' under traceDetail component

### PR DESCRIPTION
**Pull request by horber**

### CODE REVIEW

**Comment by Fine0830** [comment]
I don't think we need this. Close side boxes by the `x` and the backdrop. Double click is easy to cause mis-operation.

**Comment by horber** [comment]
where is the backdrop，I feel that except for X, clicking anywhere has no effect. However, the current area of X is very small, and the user experience is not very good

**Comment by wu-sheng** [comment]
I think she means all these space, 
image

**Comment by horber** [comment]
I prefer to use shortcut keys, such as ESC, but there are problems with binding Keyup events. Do you have any better way to improve the user experience @Fine0830

**Comment by horber** [comment]
image
In fact,  The page looks like this

**Comment by Fine0830** [comment]
If you like, you can add a button to close a side box.
test

**Comment by horber** [comment]
image
Could we adjust it so that there is 10% space on the right side to close the shell layer, and the operation efficiency will be much higher @Fine0830

**Comment by wu-sheng** [comment]
Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.

**Pull request closed without merging**
