### PR TITLE
fix issue apache/skywalking#3588 .

### PR DESCRIPTION
**Pull request by dominicqi**
When query endpointTopology return .
Use `org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery#getEndpointInfo` query EndpointInfo by endpointId ,then add EndpointInfo.serviceName to the node.value for display.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you give us a screenshot?

**Comment by dominicqi** [comment]
> Could you give us a screenshot?

image
Here is the screenshot.

**Comment by wu-sheng** [comment]
This is acceptable. @x22x22 @TinyAllen Please review.

**Comment by x22x22** [comment]
@wu-sheng @dominicqi 
I am worried that this method will cause the information to be displayed too long and will affect the image display. I suggest trying to use the visualMap property of echarts to see if this problem can be solved.

我担心这种方式会导致信息显示过长会影响图像展示，我建议尝试使用echarts的visualMap属性看看是否可以解决这个问题。

**Comment by wu-sheng** [comment]
> I am worried that this method will affect the image display when the endpoint and node.value are too long. I suggest using the visualMap property of echarts. If visualMap cannot be done or is difficult, it is recommended to put node.value in the tooltip.

Make sense. In the tooltip, you should indicate this is `service: xyz`.

**Comment by x22x22** [comment]
@dominicqi pls clear warring:
https://github.com/apache/skywalking-rocketbot-ui/pull/164/checks?check_run_id=256409226#step:4:48

**Comment by dominicqi** [comment]
> @dominicqi
> Please clear the warning caused by incorrect code style, thank you!
> https://travis-ci.org/apache/skywalking-rocketbot-ui/builds/596530088#L283
image


Do you means  such a visualMap?

**Comment by x22x22** [comment]
> > @dominicqi
> > Please clear the warning caused by incorrect code style, thank you!
> > https://travis-ci.org/apache/skywalking-rocketbot-ui/builds/596530088#L283
> > image
> 
> Do you means such a visualMap?

cool! but can VisualMAP position  on top?

**Comment by dominicqi** [comment]
> > > @dominicqi
> > > Please clear the warning caused by incorrect code style, thank you!
> > > https://travis-ci.org/apache/skywalking-rocketbot-ui/builds/596530088#L283
> > > image
> > 
> > 
> > Do you means such a visualMap?
> 
> cool! but can VisualMAP position on top?

[https://echarts.apache.org/zh/option.html#visualMap-piecewise.align](visualMap)
piecewise visualMap not support  align  `top`.

**Comment by x22x22** [comment]
> > > > @dominicqi
> > > > Please clear the warning caused by incorrect code style, thank you!
> > > > https://travis-ci.org/apache/skywalking-rocketbot-ui/builds/596530088#L283
> > > > image
> > > 
> > > 
> > > Do you means such a visualMap?
> > 
> > 
> > cool! but can VisualMAP position on top?
> 
> [https://echarts.apache.org/zh/option.html#visualMap-piecewise.align](visualMap)
> piecewise visualMap not support align `top`.

try top:0

**Comment by dominicqi** [comment]
> > > > > @dominicqi
> > > > > Please clear the warning caused by incorrect code style, thank you!
> > > > > https://travis-ci.org/apache/skywalking-rocketbot-ui/builds/596530088#L283
> > > > > image
> > > > 
> > > > 
> > > > Do you means such a visualMap?
> > > 
> > > 
> > > cool! but can VisualMAP position on top?
> > 
> > 
> > [https://echarts.apache.org/zh/option.html#visualMap-piecewise.align](visualMap)
> > piecewise visualMap not support align `top`.
> 
> try visualMap.top properties, see https://www.echartsjs.com/examples/zh/editor.html?c=bar-brush

image
got it,thank you!

**Comment by wu-sheng** [comment]
@dominicqi This PR is merged, could you work on a new PR in main repo to update UI submodule?

**Pull request merged**
