### PR TITLE
Feat: Implement service logs in ui

### PR DESCRIPTION
**Pull request by Fine0830**
Implement service logs in ui. Reference https://github.com/apache/skywalking/issues/5930

Screenshots

link

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
1. Let's keep the trace Id at the last column in the main page.
2. We need to add 2 buttons to support visualizing trace related logs on the trace and span page. At there, we use `trace_id` and `trace_id + segment_id + span_id` to open a new pop up page to show.

**Comment by Fine0830** [comment]
> 1. Let's keep the trace Id at the last column in the main page.

Done

**Comment by Fine0830** [comment]
> 2. We need to add 2 buttons to support visualizing trace related logs on the trace and span page. At there, we use `trace_id` and `trace_id + segment_id + span_id` to open a new pop up page to show.

I will handle this in another pr to make this pr smaller.

**Comment by Fine0830** [comment]
Please recheck

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
