### PR TITLE
fix: update selector keys for duplicate options

### PR DESCRIPTION
**Pull request by Fine0830**
Fixes https://github.com/apache/skywalking/issues/7147#issuecomment-864915908

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
@start1943  You could test this, but still, your ElasticSearch issue should be paid attention to.

**Review by wu-sheng — APPROVED** [review]

**Comment by start1943** [comment]
Since I deleted the SERVER_TRAFFIC index yesterday to fix the duplicate data, I cannot test whether the service option conflict is still a problem, but I find that the endpoint selection is still a problem. Selecting a keyword to query the page will still get stuck.

**Comment by start1943** [comment]
image

**Comment by wu-sheng** [comment]
> Selecting a keyword to query the page will still get stuck.

This is fixed issue.

**Comment by start1943** [comment]
I know， that the above img was built and tested with the latest master code

**Comment by start1943** [comment]
when SERVER_TRAFFIC index have duplicate data, in trace tab ,choose service is still have problem，Is Dashboard compatible with this situation？ @Fine0830 @wu-sheng

**Comment by start1943** [comment]
I have checked the index data in ES .  the SW_SERVICE_TRAFFIC index automatically delete the previous history data? But I found that the data of the  yesterday did not trigger deletion, This will trigger a duplicate error？

**Comment by wu-sheng** [comment]
> I have checked the index data in ES .  the SW_SERVICE_TRAFFIC index automatically delete the previous history data? But I found that the data of the  yesterday did not trigger deletion, This will trigger a duplicate error？

No, it isn't. Once it exists, it should not be inserted again. That is what I mean you ES has issue.

**Comment by wu-sheng** [comment]
SERVER_TRAFFIC is not an index, it is a template.

**Comment by start1943** [comment]
yes,i know, There are a lot of duplicate data between the index data of my ES index today and yesterday, and the data in the previous index were all 0, so I guess may be automatically delete the previous history data? In short, is Dashboard compatible with this exception。。

**Comment by wu-sheng** [comment]
Please don't keep saying things repeatedly.
I am really frustrated to track here, as you never take a look at what I said, and give a feedback.
I am out.

**Pull request merged**
