### PR TITLE
Feat: Support tag conditions for trace

### PR DESCRIPTION
**Pull request by Fine0830**
Support tag conditions for trace. Reference https://github.com/apache/skywalking/issues/5272

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please give a separate line for the tag condition, because users usually use multiple tags.

And could you show me, how to input the tag(key=vlaue)? Such as, please consider value could include `white space` in some cases. Traditionally, the interactive style is, user gives `key=value`, value could be anything following the first `=`. Then use `enter` to confirm the condition added. And you would have an `x` after the condition set. I think you used to do similar things in the comparison page.

**Comment by Fine0830** [comment]
> Please give a separate line for the tag condition, because users usually use multiple tags.
> 
> And could you show me, how to input the tag(key=vlaue)? Such as, please consider value could include `white space` in some cases. Traditionally, the interactive style is, user gives `key=value`, value could be anything following the first `=`. Then use `enter` to confirm the condition added. And you would have an `x` after the condition set. I think you used to do similar things in the comparison page.

For multiple tags, we use a separate comma. As follow,

**Comment by wu-sheng** [comment]
The way I suggested because we don't know comma or whitespace whether be a part of tag value.

**Comment by Fine0830** [comment]
The pr was updated, please recheck @wu-sheng

**Comment by wu-sheng** [comment]
@Fine0830 Please sync the main repo, I could update the demo env later.

**Pull request merged**
