### PR TITLE
Solve the problem that traceId stored in localstorage cannot be deleted

### PR DESCRIPTION
**Pull request by horber**

### CODE REVIEW

**Comment by Fine0830** [comment]
I can't reproduce this on my side. Could you describe the problem in detail? @horber

**Comment by horber** [comment]
image
First delete 'x' from the input box, then search and refresh the page. You will find that 'x' appears again

**Comment by Fine0830** [comment]
> image
> First delete 'x' from the input box, then search and refresh the page. You will find that 'x' appears again

There are no problems. If you change or remove `traceId`, you should click the Search or Clear button.

**Comment by horber** [comment]
> traceId

image
The problem here is, in the 'this.traceId' We also need to update localstorage when it is false

**Review by Fine0830 — APPROVED** [review]

**Pull request merged**
