### PR TITLE
set dateformat with timezone

### PR DESCRIPTION
**Pull request by xbkaishui**
fix bug [5423](https://github.com/apache/skywalking/issues/5423), when change the timzone, 
the return trace data not change.

### CODE REVIEW

**Comment by xbkaishui** [comment]
currently I only changed the trace page date time,  didn't fix the calendar picker component

**Comment by wu-sheng** [comment]
@Fine0830 Please take a look. @TinyAllen seems a little busy these days.

**Review by TinyAllen — APPROVED** [review]
lgtm

**Comment by Fine0830** [comment]
I found there is a bug and no data(dashboard, trace, alarm) change. I think we should use global `SET_EVENTS` to update data when we change the timezone.

**Comment by Fine0830** [comment]
@xbkaishui Could you submit pr again for https://github.com/apache/skywalking/issues/5423

**Comment by xbkaishui** [comment]
> I found there is a bug and no data(dashboard, trace, alarm) change. I think we should use global `SET_EVENTS` to update data when we change the timezone.

Sorry, didn't get your point, which page is no data change ?

**Comment by xbkaishui** [comment]
For this pr, I just changed the data format logic, nothing else.

**Comment by Fine0830** [comment]
@xbkaishui The time data haven't changed.

**Comment by xbkaishui** [comment]
like I mentioned above,  didn't fix the calendar picker component, because I am not familar with this

**Pull request merged**
