### PR TITLE
Support for apache-servicecomb

### PR DESCRIPTION
**Pull request by surechen**
Support for apache-servicecomb icon.

### CODE REVIEW

**Comment by wu-sheng** [comment]
LGTM, do you have a screenshot to verify this?

**Comment by surechen** [comment]
> LGTM, do you have a screenshot to verify this?

I will verify this later. Thanks.

**Comment by wu-sheng** [comment]
Any update? No update in 23 days.

**Comment by surechen** [comment]
> Any update? No update in 23 days.

不好意思，有些事情耽搁了，我用带pr的版本尝试，没有获得预期的效果

**Comment by wu-sheng** [comment]
Are you included the submodule update?

**Comment by surechen** [comment]
> Are you included the submodule update?

这里是指apache/skywalking项目的模块吗？我是在oap-server/server-starter/src/main/resources/component-libraries.yml文件中添加
# Golang components
# [5000, 6000) for Golang agent
ServiceCombMesher:
  id: 5001
  languages: Golang
ServiceCombServiceCenter:
  id: 5002
  languages: Golang
然后在按文档介绍编译运行：
git submodule init
git submodule update
 ./mvnw clean package -DskipTests
使用 /dist 下面的 .tar.gz for Linux 运行
请问我是否还有其他需要注意的我没有关注？

**Comment by wu-sheng** [comment]
git submodule update is just syncing to the current version. As you change the submodule in this repo, you need to `git pull` your PR branch to change the submodule commit id. Otherwise, you are still using the official master code.

**Comment by surechen** [comment]
> git submodule update is just syncing to the current version. As you change the submodule in this repo, you need to `git pull` your PR branch to change the submodule commit id. Otherwise, you are still using the official master code.

Verified pictures here:
image

**Pull request merged**
