### PR TITLE
Feat: Update alarm scope

### PR DESCRIPTION
**Pull request by TinyAllen**
image

### CODE REVIEW

**Comment by TinyAllen** [comment]
@mrproliu  Do we need to add this DatabaseAccess scope？

**Comment by wu-sheng** [comment]
@mrproliu Does Database save in service?

**Comment by mrproliu** [comment]
> @mrproliu Does Database save in service?

Yes, It's using service scope.

**Comment by mrproliu** [comment]
image

Here is a database access example. It's using service scope.

**Comment by wu-sheng** [comment]
Could you test this PR with your all Local alarm?

**Comment by mrproliu** [comment]
> Could you test this PR with your all Local alarm?

I have a quick test, it works well. but we don't need the database access in this selection, we need to remove it.
image

**Pull request merged**
