### PR TITLE
feat: Implement a timeline for Events in a new page

### PR DESCRIPTION
**Pull request by Fine0830**
Closes https://github.com/apache/skywalking/issues/7066

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
Thanks @Fine0830 !

**Comment by wu-sheng** [comment]
@kezhenxu94 @Fine0830 
image

Is this expected to be like this? A new line I mean.

**Comment by Fine0830** [comment]
> @kezhenxu94 @Fine0830
> image
> 
> Is this expected to be like this? A new line I mean.

Yep. it's consistent with Alarm events details.

**Comment by wu-sheng** [comment]
I know, I just mean the layout. It makes me feeling an empty accidentally added :)

**Comment by Fine0830** [comment]
> I know, I just mean the layout. It makes me feeling an empty accidentally added :)

Let me fix this.

**Pull request merged**
