### PR TITLE
Feat: merge P50-99 into percentile metric

### PR DESCRIPTION
**Pull request by Fine0830**
Merge P50-99 into one metric.
reference  https://github.com/apache/skywalking/issues/4219

screenshots
屏幕快照 2020-01-13 下午4 27 36
屏幕快照 2020-01-13 下午4 27 51
屏幕快照 2020-01-13 下午4 28 10
屏幕快照 2020-01-13 下午4 28 36
屏幕快照 2020-01-13 下午4 28 59
屏幕快照 2020-01-13 下午4 29 25
屏幕快照 2020-01-13 下午4 29 37
屏幕快照 2020-01-13 下午4 34 49

### CODE REVIEW

**Comment by wu-sheng** [comment]
Cool!!! How quickly you are.

**Comment by Fine0830** [comment]
After merging P50-99 into percentile metric, UI decrease many codes and logic. It's more clear.

**Comment by wu-sheng** [comment]
Noticed :) Surprisingly good for UI. Should I merge this now?

**Comment by wu-sheng** [comment]
Please sync to the main repo. :) Thanks for your fast fix.

**Comment by Fine0830** [comment]
OK

**Pull request merged**
