### PR TITLE
Feat: Implement endpoint dependency and metrics

### PR DESCRIPTION
**Pull request by Fine0830**
Implement endpoint dependency and metrics in topology page. Reference https://github.com/apache/skywalking/issues/4905

Screenshots
topo
sankey

Signed-off-by: Qiuxia Fan  <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please rename 
- SLA -> Successful Rate
- Avg Throughput -> Load (CPM - calls per minute)

And where is the `depth`? It should determine, how many times you should query at `upstream` and `downstream` sides.

**Comment by wu-sheng** [comment]
And please use linear graph to represent the successful rate, like the latest dashboard.

image

**Comment by wu-sheng** [comment]
And another question for this, why `/projectB` endpoint doesn't have upstream endpoint? This doesn't match the reality.

**Comment by Fine0830** [comment]
The PR was updated. @wu-sheng

**Comment by wu-sheng** [comment]
Cool!!! I am going to merge this, please update the submodule.

**Pull request merged**
