### PR TITLE
feat: implement Events in dashboard

### PR DESCRIPTION
**Pull request by Fine0830**
Implement Events in dashboard with lists in a popup. Add markAreas in charts with events data. Reference https://github.com/apache/skywalking/issues/5980

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
1. Make the event option at the top level, right top.
2. User only needs to choose Event levels(Service/Instance/Endpoint), rather than specific events.
3. Event should be available on the dashboard of the topology page.

**Comment by Fine0830** [comment]
Done. Please recheck.

**Comment by wu-sheng** [comment]
Please fix the conflicts.

**Comment by wu-sheng** [comment]
@kezhenxu94 This is closing to test.

**Comment by Fine0830** [comment]
Done

**Comment by kezhenxu94** [comment]
Some observations:

- [ ] Hitting the "Reload" button doesn't reload the events.
- [ ] Refresh the browser doesn't re-select all the events.
Screen Shot 2021-04-02 at 12 43 08

- [ ] When there is > 8 events in the time range, the layout becomes messy.
Screen Shot 2021-04-02 at 12 50 01

**Comment by Fine0830** [comment]
Done

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
