### PR TITLE
Feat: Implement browser metrics in dashboard

### PR DESCRIPTION
**Pull request by Jtrust**
- [x] New feature provided
Implement browser metrics in dashboard [#5228](https://github.com/apache/skywalking/issues/5228)

### CODE REVIEW

**Comment by Jtrust** [comment]
WX20200912-225311@2x

**Comment by wu-sheng** [comment]
Logs query should move into another top tab.

**Comment by Jtrust** [comment]
WX20201008-081339@2x
screenshots

**Comment by wu-sheng** [comment]
@Jtrust From the screenshot, the comments are following,

1. error info and stack should support multiple lines and width changable.
1. The order of columns should be `time`, `service`, `error`, `stack`, `version`, `url`, `catalog`, and `grade`.
1. The column separator breaks.
1. We should be clear, what is `line` and `col` for, @Fine0830 
1. Every char of the words in the title should be upper case, take a look at the trace table view page.

**Comment by wu-sheng** [comment]
> We should be clear, what is line and col for

The line and column should be targeting `url`, so, should have a part of URL, `/index.html (line, xxx. column, yyy)` @Fine0830 Does this make sense?

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Please fix the log page error later.

**Pull request merged**
