### PR TITLE
After changing the durationTime, the topology shows the originally selected group or service. 

### LINKED ISSUE #489: After changing the durationTime, the topology shows the default again.
After changing the durationTime, the topology again displays all the services of the first group by default. 
I think it should show the topological of the group or service originally selected.

### PR DESCRIPTION
**Pull request by heihaozi**
Fix #489

### CODE REVIEW

**Comment by wu-sheng** [comment]
@heihaozi Your commit logs are not clean.

**Comment by heihaozi** [comment]
> 
> 
> @heihaozi Your commit logs are not clean.

Only the last submission is valid, and the others are all merged [apache/skywalking-rocketbot-ui](https://github.com/apache/skywalking-rocketbot-ui/) updates.

**Comment by wu-sheng** [comment]
> > @heihaozi Your commit logs are not clean.
> 
> Only the last commit is valid, and the others are all merged [apache/skywalking-rocketbot-ui](https://github.com/apache/skywalking-rocketbot-ui/) updates.

You should learn how to sync upstream about git. All these revert PRs are not recommended way, which makes the commit log look strange.

**Comment by heihaozi** [comment]
> 
> 
> > > @heihaozi Your commit logs are not clean.
> > 
> > 
> > Only the last commit is valid, and the others are all merged [apache/skywalking-rocketbot-ui](https://github.com/apache/skywalking-rocketbot-ui/) updates.
> 
> You should learn how to sync upstream about git. All these revert PRs are not recommended way, which makes the commit log look strange.

All right!

**Review by Fine0830 — APPROVED** [review]

**Pull request merged**
