### PR TITLE
Better distinguish between upstream and downstream services. 

### LINKED ISSUE #467: Cannot distinguish between upstream and downstream services.
When selecting a service in the topology diagram, all the services are displayed together.

 As shown below: 

Cannot distinguish between upstream and downstream services.

### PR DESCRIPTION
**Pull request by heihaozi**
Fix #467 

When a service is selected or there is only one service in the selected group, the upstream and downstream services are displayed separately. 

Before fix:

After fix:

### CODE REVIEW

**Comment by wu-sheng** [comment]
I am not very sure about adding this, to be honest. This dataflow graph seems only useful in very limited scenarios, and users would become to think, all dataflow should be like this. 
I don't want to mislead the community and make ourselves facing a lot of meaningless questions.

**Comment by heihaozi** [comment]
Well, it is a good idea for ourselves, but it may not be for the community.

**Comment by wu-sheng** [comment]
Let's not delete this PR for months. If more people reply here and explain the case, we could decide later.

**Comment by wu-sheng** [comment]
Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.

**Pull request closed without merging**
