### PR TITLE
python psycopg plugin

### PR DESCRIPTION
**Pull request by tom-pytel**
Icon for python psycopg plugin.

### CODE REVIEW

**Comment by kezhenxu94** [comment]
PSYCOPG is licensed under LGPL, so I guess the logo is the same, can you please check?

**Comment by kezhenxu94** [comment]
Well, with the license, I'm wondering whether we could just fall it through a generic component, like Postgresql

**Comment by wu-sheng** [comment]
> PSYCOPG is licensed under LGPL, so I guess the logo is the same, can you please check?

Agree, it is better to keep us away from LGPL.

**Comment by tom-pytel** [comment]
Converted to generic PostgreSQL component in https://github.com/apache/skywalking-python/pull/122

**Pull request closed without merging**
