### PR TITLE
 Fix the error of server response time in the topology.

### LINKED ISSUE #513: There is an error of server response time in the topology.
I think there is an error of server response time in the topology.

### PR DESCRIPTION
**Pull request by heihaozi**
Fix #513

### CODE REVIEW

**Comment by wu-sheng** [comment]
@Fine0830 Why there are metrics still hardcoded today?

**Comment by Fine0830** [comment]
> @Fine0830 Why there are metrics still hardcoded today?

It's for computing the topology itself. I haven't updated code in the 8.6.0.

**Comment by Fine0830** [comment]
Shall we use the v2 metric protocol to instead v1 metric protocol?

**Comment by wu-sheng** [comment]
> > @Fine0830 Why there are metrics still hardcoded today?
> 
> It's for computing the topology itself. I haven't updated code in the 8.6.0.

We should, but it is not urgent. Then this PR seems a correct fix?

**Comment by Fine0830** [comment]
> > > @Fine0830 Why there are metrics still hardcoded today?
> > 
> > 
> > It's for computing the topology itself. I haven't updated code in the 8.6.0.
> 
> We should, but it is not urgent. Then this PR seems a correct fix?

Yep. Looks good to me.

**Review by Fine0830 — APPROVED** [review]

**Pull request merged**
