### PR TITLE
feat: Support search and visualize alarms with tags

### PR DESCRIPTION
**Pull request by Fine0830**
Reference https://github.com/apache/skywalking/issues/6821

Screenshot

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
@liqiangz Could you test and recheck this?

**Review by wu-sheng — APPROVED** [review]
Let's merge and sync this.

**Comment by liqiangz** [comment]
> @liqiangz Could you test and recheck this?

@wu-sheng I will recheck this later.

**Comment by liqiangz** [comment]
@wu-sheng  It works fine.
image
image

**Pull request merged**
