### PR TITLE
add Flask logo/icon

### PR DESCRIPTION
**Pull request by alonelaval**
[reference pull request](https://github.com/apache/skywalking-python/pull/31)

### CODE REVIEW

**Comment by wu-sheng** [comment]
The icon is too large, please use the small one.

**Comment by alonelaval** [comment]
> The icon is too large, please use the small one.

ok

**Comment by kezhenxu94** [comment]
@alonelaval the last step is adding a component definition in the main repo https://github.com/apache/skywalking/blob/31f42343f6f38ca4838a02866be3bdde7fc3d12a/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L395-L397

**Comment by alonelaval** [comment]
> @alonelaval the last step is adding a component definition in the main repo https://github.com/apache/skywalking/blob/31f42343f6f38ca4838a02866be3bdde7fc3d12a/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L395-L397

ok

**Pull request merged**
