### PR TITLE
optimize rk-icon

### PR DESCRIPTION
**Pull request by xuchangjunjx**
1. fix the rk-footer utc input's width too small 
2. replace svg tag with rk-icon in component rk-header
3. update component  rk-icon.vue

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you provide screenshot or gif to show what do you fix?

**Comment by xuchangjunjx** [comment]
> Could you provide screenshot or gif to show what do you fix?

The Old:

old

The new:
image

className `vm` just set `vertical-align: middle;` , and className `icon` has included

**Comment by wu-sheng** [comment]
@Fine0830 Please take a look.

**Review by Fine0830 — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
@xuchangjunjx Could you submit a pull request to sync the main repo?

**Comment by xuchangjunjx** [comment]
> @xuchangjunjx Could you submit a pull request to sync the main repo?

合到075b29fce4上吗还是直接clone @apache/skywalking ? 😄

**Comment by wu-sheng** [comment]
Clone apache/skywalking and update the UI submodule. It uses git submodule.

**Pull request merged**
