### PR TITLE
add envoy proxy component logo.

### PR DESCRIPTION
**Pull request by JaredTan95**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you compress this? +48.7 KB is not a small icon. And please provide a screenshot.

**Comment by JaredTan95** [comment]
> Could you compress this? +48.7 KB is not a small icon. And please provide a screenshot.

Agree, and I changed one small size, only 4kb.

**Comment by JaredTan95** [comment]
preview image: envoy

**Comment by wu-sheng** [comment]
I mean the screenshot of topology. It is better to check how it looks there.

**Comment by JaredTan95** [comment]
> I mean the screenshot of topology. It is better to check how it looks there.

image

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
