### PR TITLE
Add micro logo

### PR DESCRIPTION
**Pull request by zaunist**

### CODE REVIEW

**Comment by wu-sheng** [comment]
What is this logo for?

**Comment by zaunist** [comment]
> What is this logo for?

https://github.com/SkyAPM/go2sky-plugins/tree/master/micro

**Comment by wu-sheng** [comment]
Why is `mu` as the icon? I haven't found the icon at the project page, https://go-micro.dev/

**Comment by zaunist** [comment]
> Why is `mu` as the icon? I haven't found the icon at the project page, https://go-micro.dev/

Micro is a runtime tool set written using the go-micro framework. It's main role is to assist in the development of microservices. This is micro official website  https://micro.mu/ ,there is only this icon.And  I downloaded the icon from here https://github.com/micro/micro/blob/master/docs/images/logo.png

**Comment by wu-sheng** [comment]
I think you are referring to the wrong place? micro.mu is not the plugin for.

**Comment by zaunist** [comment]
I updated the micro icon, please review it @wu-sheng

**Comment by wu-sheng** [comment]
Could you share how it looks like in the topology?

**Comment by zaunist** [comment]
image

**Comment by zaunist** [comment]
This is what the go-micro icon shows

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Please sync the submodule in the main repo.

**Pull request merged**
