### PR TITLE
Feat: implement viewing logs on trace page

### PR DESCRIPTION
**Pull request by Fine0830**
Implement viewing logs on trace page. Reference https://github.com/apache/skywalking/issues/5930

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by Fine0830** [comment]
Please check @wu-sheng @zhangkewei

**Comment by wu-sheng** [comment]
Logs on the trace page should only related the trace_id.

**Comment by Fine0830** [comment]
> Logs on the trace page should only related the trace_id.

Done

**Comment by wu-sheng** [comment]
Great. I think it is good now.

**Review by wu-sheng — APPROVED** [review]
Let's merge and sync to the main repo.

**Pull request merged**
