### PR TITLE
Update: update utc & duration

### PR DESCRIPTION
**Pull request by TinyAllen**
1. UTC change from '-12 ~ +12' to '-12 ~ +14'.
2. Change global duration.
3. Change topology SLA threshold (99.99% => 98%).

**!!!**  Need a careful recheck all the charts, I'm afraid there will be duration mistakes that I overlook.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@JaredTan95 Could you lead this test? By using docker with UTC 0(or other timezone), recheck all graphs, trace page, alarm, topology. To see whether all time stamp shows correctly.

**Comment by wu-sheng** [comment]
The best way to test this is integration tests based on the container.

**Comment by JaredTan95** [comment]
Hi, @TinyAllen 

I have tested in my local env. And there are something query statement wrongs.

1. Switching time zone does not take effect in `Trace`.

CC @wu-sheng

**Comment by JaredTan95** [comment]
I rechecked in my local env, and all looks good to me. 

image

image

image
image

image

**Comment by JaredTan95** [comment]
BTW, I found `refresh` button looks like doesn't works well. Need your check. :P

**Comment by JaredTan95** [comment]
image

LGTM

**Comment by wu-sheng** [comment]
Thank you both. Please submit submodule update

**Pull request merged**
