### PR TITLE
refactor: header menu render

### PR DESCRIPTION
**Pull request by ruibaby**
1. Render the top menu based on the route mapping, Not hard-coded.
2. Create i18n config files for easy use in other js or ts files.
3. Refactor the route mapping, Dynamically import routing components, Improve first page loading performance.

### CODE REVIEW

**Review by Fine0830 — COMMENTED** [review]
Here the input has lost its style. Other codes are good to me.
test

**Comment by ruibaby** [comment]
> Here the input has lost its style. Other codes are good to me.

ok, I will try to solve. It is the style of the profile page that affects the style of the dashboard .

**Comment by ruibaby** [comment]
@Fine0830 Resolved some style conflicts, But I’m not sure if there are other things I haven’t observed, I recommend using scoped markup on some specific components. 

thw, for some basic styles, I recommend https://github.com/tailwindlabs/tailwindcss, Can resolve style conflicts to a large extent.

**Comment by Fine0830** [comment]
@ruibaby I don't think they are style conflicts. As you use dynamically import, some global style lose in components. If you would like to use dynamically import, please sorting out global styles.
test

**Comment by ruibaby** [comment]
@Fine0830 Ok, i will try my best to solve this problem.

**Comment by ruibaby** [comment]
I have checked all the page styles, The incorrect place has made modifications, In addition, I found that there are several places that may need to be discussed because I am not sure if the modification is correct.

/trace:

image
image
image


/profile:
image


If we need to refactor all styles, I don't recommend operating in this PR.

**Comment by Fine0830** [comment]
Could you modify the styles you mentioned above to make them consistent with the demo environment? We found some changes in other components later.

**Comment by wu-sheng** [comment]
@ruibaby If you want to discuss the improvement, choose to use another new PR. Please make the changes as your title described.

**Comment by ruibaby** [comment]
@Fine0830 @wu-sheng Okay, I'll change it to be the same as the online demo.

> We found some changes in other components later.
@Fine0830 such as? I will check it out.

**Comment by Fine0830** [comment]
What I mean is to change the style problems found, and update the other style problems when they are found later. Now I haven't found any other problems.

**Comment by ruibaby** [comment]
Has been modified.

**Comment by Fine0830** [comment]
There are two pages to need to fix the style.




@ruibaby Enter the above pages by two icons.

**Comment by ruibaby** [comment]
@Fine0830 Has been modified.

**Review by Fine0830 — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
@ruibaby Please update the main repo's UI submodule, then we could include your changes in the demo env.

**Comment by ruibaby** [comment]
> @ruibaby Please update the main repo's UI submodule, then we could include your changes in the demo env.

Okay, on my way.

**Pull request merged**
