### PR TITLE
Fix:browser console error

### PR DESCRIPTION
**Pull request by bigflybrother**
when endpoints is null, browser console error ,
https://github.com/apache/skywalking-rocketbot-ui/issues/182

### CODE REVIEW

**Comment by TinyAllen** [comment]
could you please put a screenshot?

**Comment by bigflybrother** [comment]
image

**Comment by wu-sheng** [comment]
@bigflybrother Have you tried the latest master codes?

**Comment by wu-sheng** [comment]
Is this error caused by no endpoint registered yet?

**Comment by bigflybrother** [comment]
yes

**Comment by TinyAllen** [comment]
In this way may case other problem. This issue #182 i will fix it soon.

**Pull request closed without merging**
