### PR TITLE
feat: remove node-sass, use dart-sass

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**
https://sass-lang.com/dart-sass

> Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. It's fast, easy to install, and it compiles to pure JavaScript which makes it easy to integrate into modern web development workflows. Find out more or help out with its development on GitHub.

https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0

> prefer sass (dart-sass) by default, it is strongly recommended to migrate on sass (dart-sass)

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@kezhenxu94 any update?

**Comment by kezhenxu94** [comment]
@Jtrust can you take a look?

**Comment by Jtrust** [comment]
> @Jtrust can you please take a look?

It works fine on my PC. And I searched for some relevant information.
 [The performance evaluation](https://github.com/sass/dart-sass/blob/master/perf.md)
[dart-sass in vue-cli](https://github.com/vuejs/vue-cli/pull/3321)
[the future of sass](https://sass-lang.com/blog/announcing-dart-sass)
The underlying dependency of Node-Sass on libsass makes  installation difficult for some users, especially Windows users. dart-sass is a good way to avoid this problem.
The compatibility width `/deep/` to `::v-deep` is not involved in this project.
I think that we could change node-sass to dart-sass.

**Review by kezhenxu94 — APPROVED** [review]

**Comment by kezhenxu94** [comment]
Thanks @Jtrust for confirming

**Pull request merged**
