### PR TITLE
feat: extend table chart

### PR DESCRIPTION
**Pull request by Fine0830**
Extends table chart, including style, zoom width, add config, and copy data.

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
@wankai123 Please take a look.

**Comment by wankai123** [comment]
what's the symbol `<···>` meaning?
image

**Comment by wu-sheng** [comment]
> what's the symbol `<···>` meaning? @Fine0830
> image

Scrollable. Put the mouse on it, you will see.

**Comment by wankai123** [comment]
could we give some styles to the `table header` row, to identity it's a header?
image

**Review by wu-sheng — APPROVED** [review]
@Fine0830 I am going to merge this first for testing. You could add some style after the event feature or including it in that PR.

**Pull request merged**
