### PR TITLE
add go-kartos component logo

### PR DESCRIPTION
**Pull request by kagaya85**
part of https://github.com/apache/skywalking/pull/7428

ScreenShot_2021-08-10_at_14 54 46@2x

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you share the screenshot?

**Comment by wu-sheng** [comment]
Notice, once this gets merge, you need to update main repo's submodule to include this.

**Comment by kezhenxu94** [comment]
Check https://github.com/apache/skywalking/pull/7435 , you only need one logo file named `KRATOS.png`

**Comment by kagaya85** [comment]
I have only kept KRATOS.png, maybe it is better not to use mapping like GoMicroServer & GoMicroClient to void generating redundant component ids?

**Comment by kezhenxu94** [comment]
> I have only kept KRATOS.png, maybe it is better not to use mapping like GoMicroServer & GoMicroClient to void generating redundant component ids?

Which components I'd do you want to keep? 5011 or 5012?

**Comment by kagaya85** [comment]
> Which components I'd do you want to keep? 5011 or 5010?

client & server components are both needed, respectively correspond to GOKRATOSCLIENT.png and GOKRATOSSERVER.png, is this feasible?

**Comment by wu-sheng** [comment]
If they share, you need one only.

**Comment by kagaya85** [comment]
In fact for a single call, the client and server use different middleware plugins, so maybe we need two componentIDs to distinguish them?

**Comment by wu-sheng** [comment]
They are always different for any rpc framework. Check the existing plugins. But we can't find the point. Do you? What do 2 IDs help?

**Comment by wu-sheng** [comment]
@kagaya85 @kezhenxu94 What is the status of this?

**Comment by kagaya85** [comment]
> @kagaya85 @kezhenxu94 What is the status of this?

I think it is ready to merge. The icon is named as `KRATOS.png` and used only one componentID in previous merged PRs

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
