### PR TITLE
Removed "Les Miserables" from radial chart in topology.

### PR DESCRIPTION
**Pull request by zeaposs**
A small fix/tweak. I'm assuming, that "Service" is a valid label in this place.

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
I believe it's a copy-paste issue or typo, @wu-sheng could you recheck?

**Comment by kezhenxu94** [comment]
@zeaposs thanks for fixing this :)

**Comment by wu-sheng** [comment]
@zeaposs Could you update the submodule in the main repo? We are closing to release 8.3.0

**Comment by zeaposs** [comment]
Sure thing. Got stuck on the PR template, I'm not sure if I correctly filled it out - template looks completely different compared to older ui sync PRs.

**Pull request merged**
