### PR TITLE
fix: remove the no use maxItemNum for labeled-value metric, etc

### PR DESCRIPTION
**Pull request by Fine0830**
From @wankai123, remove the no use maxItemNum. 

After fixing

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
What do you remove exactly? I am confused.

**Comment by wu-sheng** [comment]
How many labels visualized for a labeled-value metric?

**Comment by Fine0830** [comment]
`maxItemNum` only works topN, `maxItemNum` value is the `N`. https://github.com/apache/skywalking-rocketbot-ui/pull/481

**Comment by wu-sheng** [comment]
> `maxItemNum` only works topN, `maxItemNum` value is the `N`. #481

Yes, this is the thing I can't confirm, and also want to make PR's title clear. 

`fix: remove the no use maxItemNum for labeled-value metric`, is this better?

**Comment by Fine0830** [comment]
Yep, it's better.

**Review by wu-sheng — APPROVED** [review]
When you sync main repo, a changelog is required.

**Comment by wankai123** [comment]
I have updated UI & clean the cache, now it doesn't show on the panel, but still in the download template @Fine0830 
image

**Comment by Fine0830** [comment]
I haven't reproduced it by using Incognito Mode.

`{"name":"Global","children":[{"width":3,"title":"Services Load","height":"300","entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_cpm","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"unit":"CPM - calls per minute","maxItemNum":10},{"width":3,"title":"Slow Services","height":"300","entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_resp_time","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"unit":"ms","maxItemNum":10},{"width":3,"title":"Un-Health Services (Apdex)","height":"300","entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_apdex","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"aggregation":"/","aggregationNum":"10000","sortOrder":"ASC","maxItemNum":10},{"width":3,"title":"Slow Endpoints","height":"300","entityType":"Endpoint","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"endpoint_avg","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"unit":"ms","maxItemNum":10},{"width":"6","title":"Global Response Latency","height":"280","entityType":"All","independentSelector":false,"metricType":"LABELED_VALUE","metricName":"all_percentile","queryMetricType":"readLabeledMetricsValues","chartType":"ChartLine","metricLabels":"P50, P75, P90, P95, P99","labelsIndex":"0, 1, 2, 3, 4","unit":"percentile in ms"},{"width":"6","title":"Global Heatmap","height":"280","entityType":"All","independentSelector":false,"metricType":"HEATMAP","unit":"ms","queryMetricType":"readHeatMap","chartType":"ChartHeatmap","metricName":"all_heatmap"},{"width":3,"title":"Title","height":350,"entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_resp_time","queryMetricType":"readMetricsValues","chartType":"ChartLine"}]}`

**Pull request merged**
