### PR TITLE
feat: optimize the style and add tips for log conditions

### PR DESCRIPTION
**Pull request by Fine0830**
Optimize the style of log conditions to resolve issues(like https://github.com/apache/skywalking/issues/7917)

Screenshot

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by Fine0830** [comment]
> Please keep time range and tips on the top.

Done

**Comment by wu-sheng** [comment]
`enter` -> `press enter`.

**Comment by wu-sheng** [comment]
Please sync main repo. After you implement cache timeout, we will update the demo env again.

**Comment by Fine0830** [comment]
> Please sync main repo. After you implement cache timeout, we will update the demo env again.

OK

**Pull request merged**
