### PR TITLE
Trace detail optimize

### PR DESCRIPTION
**Pull request by aeolusheath**
1,  highlight selected trace item
2, add action to set default empty trace
3, add loading on trace-table and trace detail page 【table and list 】

### CODE REVIEW

**Comment by wu-sheng** [comment]
@aeolusheath The main repo submodule is still not updated. Do you know how to do? I think I have asked before.

**Comment by aeolusheath** [comment]
@wu-sheng  sorry for that  last time I thought you have updated it.  emmmmm..... I didn't find proper way to update submodule in the main repo currently.

**Comment by wu-sheng** [comment]
@aeolusheath You could include this in your sync pr too.

**Comment by aeolusheath** [comment]
@wu-sheng  done

**Pull request merged**
