### PR TITLE
feat: implement searching logs with date

### PR DESCRIPTION
**Pull request by Fine0830**
Implement searching logs with date. Reference https://github.com/apache/skywalking/issues/6343

Screenshots

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Time range query should be supported in browser and service log query(s), the screenshot seems service only.

**Comment by Fine0830** [comment]
> Time range query should be supported in browser and service log query(s), the screenshot seems service only.

Done

**Comment by wu-sheng** [comment]
I want to ask, what is logic of this time range selector initialization? What is the default value every time?

**Comment by Fine0830** [comment]
> I want to ask, what is logic of this time range selector initialization? What is the default value every time?

The default value is global date in the footer.

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Please sync main repo.

**Pull request merged**
