### PR TITLE
Fix the problem that the footer and topology group is shaded when the topology radiation is displayed.

### PR DESCRIPTION
**Pull request by heihaozi**
**Fix**#445

### CODE REVIEW

**Comment by wu-sheng** [comment]
My side actually is working well. I think this has an issue only on a small screen only.

**Comment by heihaozi** [comment]
> 
> 
> My side actually is working well. I think this has an issue only on a small screen only.

When the problem is fixed, the footer and topology group is displayed like this:



Is this displayed on your side?

**Comment by wu-sheng** [comment]
I don't see the block on my browser.

**Comment by heihaozi** [comment]
My monitor is 23.8 inches. In Firefox 86.0.1 and Chrome 89.0.4389.82, the footer and topology group are all blocked.

By the way, the version of Skywalking is 8.2.0.

**Review by Fine0830 — APPROVED** [review]
LGTM

**Pull request merged**
